#ifndef QCOONNECTHELP_GLOBAL_H
#define QCOONNECTHELP_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QCONNECTHELP_LIB
# define QCOONNECTHELP_EXPORT Q_DECL_EXPORT
#else
# define QCOONNECTHELP_EXPORT Q_DECL_IMPORT
#endif

#endif // QCOONNECTHELP_GLOBAL_H
